.Dd $Mdocdate: October 15 2019$
.Dt SSH-AGENT-CARD-PROMPT 1
.Os
.Sh NAME
.Nm ssh-agent-card-prompt
.Nd intercept
.Xr ssh-agent 1
requests for SSH key signing that require tapping a physical security
key and prompt the user
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl p Ar prompt
.Sh DESCRIPTION
On startup,
.Nm
moves the current
.Xr ssh-agent 1
socket
(as set in the SSH_AUTH_SOCK environment variable)
to a temporary location and listens itself on that socket.
.Pp
When an SSH client connects,
.Nm
connects to the original ssh-agent process and proxies requests and responses
between the two.
.Pp
When
.Nm
detects an SSH_AGENTC_SIGN_REQUEST message that appears to be for a PKCS key,
it presents a modal X11 window with the
.Ar prompt
text and information about the process that is making the SSH agent connection.
.Pp
If the Escape key is pressed while presenting the dialog, the connections to
the client and ssh-agent are dropped.
If the security key is tapped, the original ssh-agent will send a response
and
.Nm
will automatically close its X11 window.
.Pp
When
.Nm
exits, the original ssh-agent socket is moved back into place.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
Print debugging messages to the terminal.
If specified twice, the contents of each message passed will be printed to the
terminal.
.It Fl p Ar prompt
The text presented to the user in the modal dialog.
Defaults to "Tap the security key to continue with signing request".
.Sh AUTHORS
.Nm
was written by
.An joshua stein Aq Mt jcs@jcs.org .
