.Dd $Mdocdate: October 15 2019$
.Dt SSH-AGENT-CARD-PROMPT 1
.Os
.Sh NAME
.Nm ssh-agent-card-prompt
.Nd
prompt the user when SSH key signing requests to an
.Xr ssh-agent 1
require tapping a physical security key (such as a YubiKey)
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl p Ar prompt
.Sh DESCRIPTION
On startup,
.Nm
moves the current
.Xr ssh-agent 1
socket (as set in the
.Ev SSH_AUTH_SOCK
environment variable) to a temporary location and creates a new socket at the
location pointed to by that variable.
.Pp
When an SSH client connects,
.Nm
connects to the original
.Xr ssh-agent 1
process and proxies requests and responses between the two.
.Pp
After
.Nm
detects and forwards an SSH_AGENTC_SIGN_REQUEST message that appears to be for
a PKCS key,
.Xr ssh-agent 1
will block while waiting for the security key to be tapped and respond to the
request.
At that point,
.Nm
will present a modal X11 window with the
.Ar prompt
text and information about the process that is making the agent connection,
reminding the user to tap the key.
.Pp
If the Escape key is pressed while presenting the dialog, the connections to
the client and ssh-agent are immediately dropped.
If the security key is tapped,
.Xr ssh-agent 1
will send its response to
.Nm
which will then automatically close its X11 window.
.Pp
When
.Nm
exits, the original ssh-agent socket is moved back to the path pointed to by
the
.Ev SSH_AUTH_SOCK
variable.
.Sh CONFIGURATION
Your security key should be configured to require touch confirmation for this
to be of any use.
.Pp
For YubiKey keys, this can be done with
.Xr yubico-piv-tool 1
by supplying
.Cm --touch-policy=always
when creating/importing keys.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
Print debugging messages to the terminal.
If specified twice, the contents of each message passed will be printed to the
terminal.
.It Fl p Ar prompt
The text presented to the user in the modal dialog.
Defaults to "Tap the security key to continue with signing request".
.Sh SEE ALSO
.Xr ssh-agent 1
.Sh AUTHORS
.Nm
was written by
.An joshua stein Aq Mt jcs@jcs.org .
